#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.
set -x
pwd
psql -d localjobs -f $OPENSHIFT_REPO_DIR/src/main/resources/create-tables.sql